name: Deploy Mainnet
on: [workflow_dispatch]
concurrency: deploy-main-relayers
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        relayer: ['1', '2', '3', '4', '5']
    steps:
    - uses: actions/checkout@v2
    - uses: rlespinasse/github-slug-action@v4
    - name: Rancher Deploy ${{ matrix.relayer }}
      uses: LATOKEN/actions-rancher-update@1.1.5
      with:
        rancher_url: ${{ secrets.RANCHER_URL_API }}
        rancher_access: ${{ secrets.RANCHER_ACCESS_KEY}}
        rancher_key: ${{ secrets.RANCHER_SECRET_KEY }}
        project_id: 1a512
        stack_name: lachain-mainnet-relayers
        service_name: relayer${{ matrix.relayer }}
        docker_image: ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:${{ env.GITHUB_REF_SLUG_URL }}
  slack:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
    - name: Send release message to slack chat
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "New release relayer-smart-contract:${{ github.ref_name }} deployed to Mainnet by ${{ github.actor }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "New release relayer-smart-contract:${{ github.ref_name }} deployed to Mainnet by ${{ github.actor }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.RELAYERS_SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
